Dockerfile
# Use OpenJDK 21 as the base image
FROM openjdk:21

# Set the working directory inside the container
WORKDIR /app

# Copy the packaged JAR application into the working directory
COPY target/wisecow-app.jar /app/wisecow-app.jar

# Expose the port the application listens on
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "wisecow-app.jar"]
